server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: "healthCare"
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true